name: Go Test

on:
  pull_request:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Set up Prometheus Pushgateway
        run: |
          curl -LO https://github.com/prometheus/pushgateway/releases/download/v1.5.2/pushgateway-1.5.2.darwin-amd64.tar.gz
          tar xvfz pushgateway-1.5.2.darwin-amd64.tar.gz
          cd pushgateway-1.5.2.darwin-amd64
          ./pushgateway &

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make -f makefile test-with-cover TestPackage=./storage/server

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./c.out